# Project information
site_name: 'Powerforce Helpdesk'
site_url: https://github.com/envizion-systems/scgs-project
site_description: Powerforce SCGS Project
repo_url: 'https://github.com/envizion-systems/scgs-project'
edit_uri: ''
site_author: Martin Drenovac
copyright: |
  Copyright &copy; 2020 <a href="#">Envizion Systems</a>
#  <br><span class="md-footer-custom-text">emoji provided free by </span><a href="http://www.emojione.com">EmojiOne</a>

nav:
  - Introduction: index.md
  - 'Project Scope':
      - 'scope01': scope_01.html

      - Delivery Platform: rest.md
      - Resourcing: resourcing.md
  - Summary: summary.md
#     - About this project: about.md
#     - Web Development:
#         - Development Platform: dev-platform.md
#         - Tech / Development Stack: tech-stack.md

#
# mkdocs configuration settings
theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  language: 'en'
  palette:
    primary: grey
    accent: dark orange

markdown_extensions:
  - fontawesome_markdown
  # Code highlighting in ``` ``` blocks
  - codehilite:
      guess_lang: true
      linenums: true
  # Table of Contents
  #- toc:
  #   permalink: false
  # block-styled side content
  - admonition
  # linkafies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  - pymdownx.magiclink
  # Task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  - pymdownx.tasklist:
      custom_checkbox: true
  # Highlight words with ==mark me==
  - pymdownx.mark
  # Adds support for deletion ~~Delete me~~ and subscript text~a\ subscript~
  - pymdownx.tilde
  # This extension is a convenience extension which includes many pymdownx extensions
  # (https://facelessuser.github.io/pymdown-extensions/extensions/extra/)
  - pymdownx.extra
  # Adds syntax for defining footnotes in Markdown documents (https://python-markdown.github.io/extensions/footnotes/)
  - footnotes
  # Adds the ability to define abbreviations
  - abbr
  # Include files in other documents like {!some/dir/in/docs/filename.md!}
  - markdown_include.include:
      base_path: docs
  # Metadata support in pages
  # (https://squidfunk.github.io/mkdocs-material/extensions/metadata/)
  - meta

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/envizion-systems'
   
extra_css: [extra.css]

plugins:
  - search
